spring:
  datasource:
    url: ${DB_URL_PROD}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    driver-class-name: ${DB_DRIVER_PROD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  server:
    port: 8080
